apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:ZKh92pr6DTIjArW+VyUoEBLbSOgT+vJLRUXlRDYu93QAHBMZNjpXifQs5fnVSJdIuA8bADnQ67psUoElOwgoUy4e49B2xwjmoP6vaq/+wYx9egJkXmnKMF4kGlmQwg1sY6nZQwVdKzWgOyUFRezJ4rFRvAxmCdH1+etHFQDoI+HiNJUmn6MygpuXJth8+7pMjHz+sLM1WkDBBtYfQKNbHozs/a/Munu0aN5P+e4FJPn9YqldQQq9NzLxj51nPbDeECNLS9Bb7cEIUqLb36JVhtrIg6WOFu7iuzufKMCHPmG2aoTbFYhD3KkvgxI=,iv:TOC1flL6C0IuQWcLgtxmv5vrI1AU2sB0af/+iHsgIxc=,tag:iTWR/Z9VFDTgJpWMKL135Q==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials-abs
sops:
    age:
        - recipient: age1pyg3dtf64zw9a3clqk6gc6zfxrlppd6wvvzyvega9599jpvupgys8hc6h8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCNTRQQXFwR05vNVdEVXZ1
            V2pNbG5tUHh5WXJmQUxsUGFDaHNTazJRZG5vClMwTUZJU2ZOUjlVZnkra25ONXdS
            ZG5KTnBhalM0dENIcTVJNjFBRkJaZjgKLS0tIGgzczZyYXdFOFV1dkIrMWgxSm8r
            VUQ4Rzhsb1VGV0VWaUhKclZFbldXSm8KzggpLzC6I6MBTtodODlJOhvh+ULIW9QJ
            h/Tb9nnPFI7CHWOuAhGhDJdQxSn5flVplj2+oGEQ1ufNmck36o8t8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T20:20:02Z"
    mac: ENC[AES256_GCM,data:Gf5WJ0xTOQPjlooUIbe3zKJ0nPCz84qp2D/F9i40V0IKgms5ZzBu12h0bU4QVxIXCn1g5Sc6lxrAQMgVgawJ2alxECzeWZPVnPQ9Zybyjsy/hKZJCteTvwNyNCFePS5Jnm6MFPXedA1QE9Y5hWvuhvlI9xlapDjfcWvZzUh0uZ8=,iv:lLjeM5GmpiYsbORp3i1VW9ixnkdhcidR3ER+JJBF6NU=,tag:2iTHq4FzdUICkgdiAsArQQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
