apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:o1ROzOSyeFmBm4Zqn4H9tTXf4TuiXhbNxcxV9ZNSXrnGOV6iX/IBz3Ai7m96SpIhVg82oagegynzXt7KXi4csDB7sMlOUz4qvAJOHbCf3Jpn1Rmre09zomBLoK3XTpMulrtnAwSAChmwaFci7AAnEdvwZEHL3UGAQgKUWwJir19/eI3sIj/rFfwxaymF85RIwGmFfRA2+9ndb5kYfqaWcFu+1AnmAUkXcMq+clNBzLPW8MchWECifgYdfNcTQk8hO6H5+gr+9yQC1NlK0SpJW2Yhz8b4M6Vzc5ybXrOPK8mKigKSW7/+upg0VZw=,iv:jeCKmkn4N793d62BMPmV4H1Yb3WtgoKPE2POeDaw/sI=,tag:p3RLa//jjl7CYVnbd+WnxA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1pyg3dtf64zw9a3clqk6gc6zfxrlppd6wvvzyvega9599jpvupgys8hc6h8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByd2RtU3R0cjlzZElVbVF4
            aE4zNFJpMlZrTDZjTnZ4ZEFlenZjemUxVWhFCmJYM0pucFh6NHZlV3JReWpSSXM0
            STFiaGV4TldNRWx4L2UxM1E5M2hNSTgKLS0tIENkcTU0TDRuUmFaRXpSY0Rka2Jm
            blN2aDJQY1VZTVVVVmhpNTd0VUZYbXcKHanc7UCvrq/tL1lCjG+WTgjd1ERBrKPC
            C3hEO0rxta8x5lJAOZn+uNKUUWWzz7WW5nflv01fBvk9dStthLNKew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T06:31:30Z"
    mac: ENC[AES256_GCM,data:vuZV3Po8HWAl/6FnwXPglGARvXEcYmY/st4RatJeAKJ+zyYmgtCcs35lAE1JiqRZE3EgKO1UuACgsJmigJs0OEfmWqQSvOQaA64wWp3UhBn77l60wHUdpQgCWaZJlu+N+O189sD9SvJX0ytOXOCaiiVTDA2tTeEt8o9EF4rHWEQ=,iv:5sWdSBMS0ikNgyuY/UMpBTB52F0HgFwScslGOf+fHpc=,tag:qauF5BKl0C/6Rg3yLZzC8g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
