apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:GgdPLM79fMrYHnTF1XNkMtUcgFDDu4YsGKbT987x59cyzBNcKOzAxfD8mmFcGXWmVydYpCvW8yJw4IUXRVcxQF1QH9nlnAwvUX95b5c9Rc2PU7yMYqKupjxq+1WDl+69cvxPLHMvZBT855hYx9cMW274wEBr4KXTHiqi/BppJaS6T/DnmCzzl7ts9EC6EY89DPLee/3g7ToQ07UvysszQRXGJMsSYdVTACVDhXLPhYXog3w+cwiAcAEm8IupvLB5PEFN83pydSS7aT3YAxkXUv5p+qSuOqzV3HahMtTAqm1z/He7swQ7yaHqeXY=,iv:FVkgTXvjyvRqLwwywjOxW+JP96dv7k0Ip82/AWbFkS8=,tag:Ma9xy0H1cjY1pIx8hO/FTw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1pyg3dtf64zw9a3clqk6gc6zfxrlppd6wvvzyvega9599jpvupgys8hc6h8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpM1ZHeTlmeFJTWHo3Q2Zw
            SDlTTGRvNTlONEZjOVMrMDVEM0tpdWNPTVRNClQ4OGhCbTgrakRIamJjQlhremNO
            TU9ySXowZTlmdjl3dDd5NlJCaDJXMFkKLS0tIGpEN2dQdHZVbU9KZXZDdFZSbDgy
            K2kwN1Rsdy96THN2K1pWbHd3d2hEU0kKwP5r247lIDjphwOCTXplKuw3w9ARNIpL
            fb+sVPeUTvl9JkJdy/nJZg/iqZuuaYyeUqEK7pqZCGTX3dxA/VcbKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T12:37:18Z"
    mac: ENC[AES256_GCM,data:Kjok9IA6e1cRkZHvYakOyZ9alvuFXxI/CawoZHdg6Pus0phxE2ATbk8+gQ+aADdWUbS6qh/n8gdnqTt+jI+mPQ6fLM2en60cNkx4hSnsNdROF50vp2HlLnluGZWgj1U0ZLhmahXez3OrRM+EvbRTl8WPUHThwlh3hWARcKh6Zio=,iv:VR3WW4u20E+KF3WNsBfIIOSJ06zwtCiKSMMTTzBUEo8=,tag:pkko4Y9pdZLz0b+Q74CLnA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
