apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:Uy6EsHbsUgY=,iv:mRmS6FKGlsc8sIUR5dVAhiyNCPNc6NiS6S4UWB8B6Mg=,tag:thtJZe/ehBvhDY4lOJSVpw==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:lp3J1MKcxCvvC/pr,iv:wMSWoDrr8rh+fsGmYHnS+uiltrbZiPsGAbw4tBKQ5cE=,tag:2eQY7lBYOOgIg2MX98pFpw==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - recipient: age1pyg3dtf64zw9a3clqk6gc6zfxrlppd6wvvzyvega9599jpvupgys8hc6h8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjc2Qvempmbm9OdXdTakRI
            OXdsOU5nMlo2eWsxdUcrMlRFbXdwODdVY0YwCnlUaTREOXQ5Z2hoTnhQSXE4Tm9G
            dTcvTTRFc2dKck5PdzlKTzQxQzE5VzQKLS0tIGk0dExrRTVaeTd4c3N4YlQ0WS83
            a1lUQnNMTGsvOTJaWWdFd0pRU3Z3K1EKXLu/UO549oFbdqjwgKIVaHVo8UnKR6b+
            6KPfuQ2h8762XOfySPnKqPHZjkWlPasiPyuNKMCzncfUCncIv/dLAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T13:06:47Z"
    mac: ENC[AES256_GCM,data:1erP/i9MqhBmcjOvYGC4vRnGhq/+V+1cL0La3TmWLHDGLYMHTPv1AHm6qedRza1/1g/OmcD09fvefy7zzMhlB0fLILEbpQNKNrYcobLd1NcQH5B/aLf7sTKVT4GXRfGsme0uvlXD9DEsiIi1ecTLiGII5D1+01ymAfEzYP732h8=,iv:GBJzVNR30gmScp+FzugKNA6nCRawXBK1osLtRPf9N6M=,tag:uqBaLnQElRzqI7sQn/qI9Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
