apiVersion: v1
data:
    password: ENC[AES256_GCM,data:Gf2z7jKMVCY=,iv:1fO+iyQy5YP5+tX9X4zqeJNOQQL78oqhN/6eeG9QlW8=,tag:pIbuYIyVkZz6UQJHlDS2OA==,type:str]
    user: ENC[AES256_GCM,data:SWMmmHUzmFY=,iv:xevxB2vUDIY/955U4Jl/Vx+pjeExA6Gzk5Sr50Troas=,tag:G5qoHvhH7AOeID5vJjH0qw==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - recipient: age1pyg3dtf64zw9a3clqk6gc6zfxrlppd6wvvzyvega9599jpvupgys8hc6h8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtMllwbGRkN2JXS3FNT2Vx
            R2ZIM252WHRTdHVibisyNHRBY1FSSXBid1c0CjVjbEFieEQvQml6d2lGUXF1Zmg3
            Qmlwa21NRWJaT3hjOVZJaURWVEtsTEkKLS0tIDFTajBKVUVXNUJqMyt3azhrUWtG
            RXZDcmE5TFZ6T2owTnRxOWtoakhyMnMKTMzX9Ykg0HaHYt+mgUk/4ZgB5BB68ACN
            jbADPeLaE8aBjETqQbuf0DvRMjQaxOWbRTg17x+j3OV63sNXlXmAXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T18:32:06Z"
    mac: ENC[AES256_GCM,data:/Sumkwojp2pdgnNRbXIfTav/PUaw5xtD5VBMwtDmfqTVaUWZwk0ECDECR4SSxVKFANUzJevZy2/kymgHrlTFiW7xUSXIFE63i1e5UTg5aysPclRfQnxNzmMvnuDPR2lYDIGlAMc3dW+ceN28vN5yZvxM2JkfZbXqbDfF/kQENz4=,iv:G/aqh2yqWT5P57cRjjWkqiXL2vId+roWaivBDvYLF9Y=,tag:ByNu4uG4hz4O8UuX8J9foQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
